//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.Download = new HashSet<Download>();
            this.Like = new HashSet<Like>();
            this.ManagePaper = new HashSet<ManagePaper>();
            this.ExpertPaper = new HashSet<ExpertPaper>();
            this.Review = new HashSet<Review>();
        }
    
        public long PaperID { get; set; }
        public Nullable<long> UpID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> UpDate { get; set; }
        public string IPC { get; set; }
        public string Abstract { get; set; }
        public string Type { get; set; }
        public Nullable<int> ReferencedNum { get; set; }
        public string DOI { get; set; }
        public string Publisher { get; set; }
        public string KeyWord { get; set; }
        public Nullable<short> HasFullText { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public string Authors { get; set; }
        public string BaiduID { get; set; }
        public Nullable<int> PublishYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Download { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Like { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagePaper> ManagePaper { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertPaper> ExpertPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
    }
}
